### ISSUE TITLE
Non-physical numerical noise when using Nm > 5

### ISSUE THREAD

**Issue by dattiyah** [fbpic/fbpic#649]
Hi,

I am running FBPIC simulations with higher order Laguerre modes (L>3), and have come across a weird bug. I am getting excessive numerical noise in m=5 as shown below. I have also attached the input deck. Any help resolving this issue would be greatly appreciated.

Thanks,
Danny Attiyah

![Figure 0](https://github.com/openPMD/openPMD-viewer/assets/70654723/5b2ef55b-960b-4efa-895a-4f224335c290)
![Figure 0(1)](https://github.com/openPMD/openPMD-viewer/assets/70654723/bdd209f1-d6cd-4f60-a803-e6864c11c80c)
![Figure 0(2)](https://github.com/openPMD/openPMD-viewer/assets/70654723/c03aa532-f16b-4164-8a8c-960a16803539)
![Figure 0(3)](https://github.com/openPMD/openPMD-viewer/assets/70654723/cb99065e-8cd8-4ea8-9bfa-b9c57ccb7b4b)
![Figure 0(4)](https://github.com/openPMD/openPMD-viewer/assets/70654723/911eb427-33ff-48bb-bad8-e68dd7d12a90)
![Figure 0(5)](https://github.com/openPMD/openPMD-viewer/assets/70654723/28c83a81-1655-4bb0-a77c-b80f01c0789d)
[input.txt](https://github.com/openPMD/openPMD-viewer/files/11748651/input.txt)

**Comment by MKirchen** [comment]
Dear @dattiyah, sorry for the late reply. You need to increase the number of particles per cell when using more modes (`nt = 4*Nm`). See als Issue #220 and #554 for additional information. Note that setting Nm > 6 can cause problems with the field solver in some simulations. Hence, we recommend setting Nm < 6. We plan to improve the implementation of the Hankel transform in the future to resolve this issue. For Nm = 5, however, the simulation should be stable.

**Comment by OwenSlevert** [comment]
Hello,

I wanted to ask if this was now solved for modes > 5 or if it is still recommended to use less than 6 modes. We are running into similar issues and do use  nt = 4*Nm.

Greetings and thank you!

**Comment by MKirchen** [comment]
Unfortunately, this is not yet fixed and requires improving the implementation of the Hankel transform to switch between the spectral and spatial representation of the fields.

**Comment by OwenSlevert** [comment]
Okay, thank you for letting me know!
